# filer
[[plugins]]
repo = 'Shougo/defx.nvim'

# icon
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# icon
[[plugins]]
repo = 'kristijanhusak/defx-icons'

# display git status on defx
[[plugins]]
repo = 'kristijanhusak/defx-git'

# file search
[[plugins]]
repo = 'Shougo/denite.nvim'

# use language server
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''


# gaming parentheses
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''

# resize window
[[plugins]]
repo = 'simeji/winresizer'

# manipulate git
[[plugins]]
repo = 'tpope/vim-fugitive'

# display git-diff on leftside
[[plugins]]
repo = 'airblade/vim-gitgutter'

# comentout selected rows
[[plugins]]
repo = 'tpope/vim-commentary'

# cool vim statusline
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  nmap <C-p> <Plug>AirlineSelectPrevTab
  nmap <C-n> <Plug>AirlineSelectNextTab
  noremap <C-q> :bdelete<CR>
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_powerline_fonts = 1
  " タブに表示する名前（fnamemodifyの第二引数）
  let g:airline#extensions#tabline#fnamemod = ':t'
'''

# vim-airline colorscheme
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme = 'light'
'''

# linter
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:airline#extensions#ale#enabled = 1
  let g:ale_sign_column_always = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
'''

# [[plugins]]
# repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
let g:rustfmt_autosave = 0
'''
on_ft = ['rust']

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    nnoremap <silent> <C-m> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kkiyama117/coc-toml'
depends = 'coc.nvim'
on_ft = 'toml'
